version: '3.8'

services:
  app:
    image: openjdk:11
    container_name: gradle_app
    volumes:
      - .:/app
    working_dir: /app
    command: ["./gradlew", "bootRun"]
    ports:
      - "8080:8080"