spring:
    application:
        name: santander-dev-week-26-03-24
    datasource:
        url: jdbc:h2:mem:sdw2024
        driver-class-name: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true